spring:
  application:
    name: FullSample

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:./db/mft_db_2;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE;MODE=MYSQL;

  jpa:
    hibernate:
      ddl-auto: create

  thymeleaf:
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    encoding: utf-8

server:
  port:
    80


